"""add profiles, mindmaps, tasks, memories, refresh tokens

Revision ID: 44708174cdb9
Revises: 83f6146de2f0
Create Date: 2026-06-17 12:04:27.542970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '44708174cdb9'
down_revision: Union[str, None] = '83f6146de2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
