"""initial schema

Revision ID: cc47a91481f1
Revises: f9423c197e41
Create Date: 2026-06-15 22:10:50.441408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cc47a91481f1'
down_revision: Union[str, None] = 'f9423c197e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
