"""add memories table

Revision ID: dc9aa120e283
Revises: 835bab866cd7
Create Date: 2026-06-16 22:15:45.457758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dc9aa120e283'
down_revision: Union[str, None] = '835bab866cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('goal', 'challenge', 'interest', 'preference', 'achievement', 'note', name='memory_category'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('chat', 'journal', 'manual', name='memory_source'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ###
