"""add mind map tables

Revision ID: e1df363030e8
Revises: 93406ec79b87
Create Date: 2026-06-16 21:21:48.338511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e1df363030e8'
down_revision: Union[str, None] = '93406ec79b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mind_maps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mind_maps_user_id'), 'mind_maps', ['user_id'], unique=True)
    op.create_table('mind_map_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('map_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['mind_maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mind_map_nodes_map_id'), 'mind_map_nodes', ['map_id'], unique=False)
    op.create_table('mind_map_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('map_id', sa.Uuid(), nullable=False),
    sa.Column('source_node_id', sa.Uuid(), nullable=False),
    sa.Column('target_node_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_label', sa.String(length=200), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['mind_maps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['mind_map_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['mind_map_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mind_map_edges_map_id'), 'mind_map_edges', ['map_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mind_map_edges_map_id'), table_name='mind_map_edges')
    op.drop_table('mind_map_edges')
    op.drop_index(op.f('ix_mind_map_nodes_map_id'), table_name='mind_map_nodes')
    op.drop_table('mind_map_nodes')
    op.drop_index(op.f('ix_mind_maps_user_id'), table_name='mind_maps')
    op.drop_table('mind_maps')
    # ### end Alembic commands ###
